import { useConfig, useTitle } from '../lib/hooks';
import { short } from '../lib/format';

export default function Docs() {
  const cfg = useConfig(); useTitle(`Docs · ${cfg?.siteName || 'Halcyon'}`);
  return (
    <main className="wrap page prose">
      <h1 style={{ fontSize: '2.4rem' }}>How Halcyon works</h1>
      <p>Halcyon is a launchpad on Ethereum mainnet. One transaction makes a coin and its Uniswap pool, with every coin of the supply in the pool from the first block and the liquidity locked forever. The pool is the curve: buys walk the price up, sells walk it back. Every trade pays the pool's 1%, and because Halcyon holds all of the pool's liquidity the whole 1% is the coin's: the gardener collects it, 20% keeps the platform and the gardener running, 80% goes where the creator aimed it.</p>

      <h2 id="pool">The pool is the curve</h2>
      <p>Every coin has 1,000,000,000 units with 18 decimals, minted once. The launch puts all of them into one single-sided position of a Uniswap pool at the 1% fee tier, starting at the market cap the creator chose in dollars ($4K, $5K, $7K, $10K or any figure from $1K to $1M), read from Chainlink's ETH/USD at that moment. From there the position runs up to the top of the price range.</p>
      <p>With a single position the pool behaves like a constant-product curve: the ETH it takes to move the cap from the start <code>M₀</code> to <code>M</code> is <code>√(M₀ × M) − M₀</code>, before fees. From $5K, about $17K of buys reach a $100K cap and about $66K reach $1M. Every ETH paid in stays in the pool, so every coin can always be sold back into it.</p>
      <p>The position is minted to a Halcyon locker (one for v3, one for v4) that has no function to withdraw or decrease it. Nobody, including Halcyon, can pull the liquidity. The coin itself has no owner, no mint, no pause, no blacklist, no tax and no max wallet.</p>
      <p>A coin's name, description, picture and links are its metadata, named on chain by the launch's <code>uri</code>.{cfg?.pinning ? <> This site pins them to IPFS at launch (the picture, then the record that names it by its content hash), so the uri is <code>ipfs://…</code>: content nobody can change or take down, which this site serves as one gateway among many.</> : <> This site hosts them at a content-addressed address of its own, immutable once written.</>} A coin launched through another front end keeps its own metadata; the site reads it from the uri.</p>

      <h2 id="pools">Two pools</h2>
      <p><b>Standard</b> is a Uniswap v3 pool of the coin against WETH. Every router and aggregator already knows how to trade it. The coin's address is chosen (through the launch's salt) to sort below WETH so the position's math is the same for every coin.</p>
      <p><b>Rules</b> is a Uniswap v4 pool of the coin against ETH with the Halcyon hook, which enforces the creator's rules on every swap, whoever routes it: an opening fee on buys that starts where the creator set it (up to 90%) and falls in a straight line to 1% over the window; a max per swap during that window; a sell fee that can stay above 1% forever; and one liquidity provider, the Halcyon locker, so every fee the pool charges is the coin's. The rules need to know nothing about who is trading, so they hold for aggregators, bots and contracts alike. A rules pool costs about 760k gas to launch; a v3 pool about 5.6M, because v3 deploys a pool contract per coin.</p>

      <h2 id="fees">The fee</h2>
      <p>Every trade pays the pool's fee: 1% on a v3 pool; on a v4 pool 1% on buys after the window, the opening fee during it, and the sell fee on sells. The fee accrues to the locked position. The gardener collects it when it is worth the gas: the coin side is sold for ETH through the same pool, and the ETH is deposited in HalcyonFees, where 20% goes to the platform pot and 80% to the coin's module. Wallet-to-wallet transfers are free; nothing is taken at launch.</p>

      <h2 id="modules">Modules</h2>
      <p>The creator chooses what the 80% becomes, and can change it later from the coin's page: <b>Roots</b> (pushed to the creator on every collect), <b>Rain</b> (paid to holders pro rata in ETH), <b>Prune</b> (buys the coin back through its own pool and burns it), <b>Harvest</b> (buys an allowed tokenized stock and pays it to holders of at least 10,000 coins), <b>Branch</b> (pushed to up to eight addresses in the creator's shares), <b>Clover</b> (the whole pot to one holder drawn by a block hash, weighted by balance), <b>Rings</b> (paid to holders weighted by balance times days held, up to thirty) and <b>Mist</b> (paid as private notes in the mist pool, spent by zero-knowledge proof to any address). The Modules page has the details of each.</p>

      <h2 id="mist">Mist</h2>
      <p>Mist is Halcyon's answer to a simple wish: to hold a coin and be paid by it without the whole chain reading your income. It is not a mixer: nothing enters the pool but Halcyon payouts, and nobody can deposit. What it hides is who was paid what, and where it went. A holder registers a mist key once: two public keys (spending and viewing, on the Baby Jubjub curve the circuit speaks), derived in the browser from one wallet signature, so the same wallet always derives the same keys and nothing has to be saved. Each round the gardener cuts every keyed holder's share into notes of the pool's denominations (0.01, 0.1 and 1 ETH on mainnet; the remainder below the smallest becomes one more note by lot, so over the rounds everyone gets exactly their due). For every note it draws a key of its own, shares a secret with the holder's viewing key (never the spending one), and sows a commitment of the holder's spending key and that secret into the pool, which hashes the batch into its Merkle tree (Poseidon, in batches of 64) and announces the note with the ephemeral key. Holders without a key are paid their exact share in the open.</p>
      <p>Finding a note takes the viewing key: one multiplication and a hash per note, in your browser. Spending one takes a proof: your browser rebuilds the tree from the public feed, and proves in zero knowledge that some leaf of the tree is a note for your spending key, revealing only a nullifier (which only the spending key can make, so a note spends once and nobody, not even the gardener, can tell which withdrawal was whose) and the destination, the relayer and the fee, which the proof binds. The site's relayer pays the gas for a fee the proof fixed (its gas plus a margin, never more than half the note), or a wallet of your own sends the proof and pays its gas. The circuit is 7,106 constraints, Groth16 over BN254; proving takes a few seconds in a browser.</p>
      <p>What is public: every note's commitment, denomination and batch, every withdrawal's amount and destination, who holds a mist key. What is not: which note is whose, and which withdrawal spent which note. What to know: the gardener computes the notes, so the platform's gardener knows who it sowed for, in memory, at that moment; it keeps no record of it and its ledger names counts, not holders. The chain cannot check a note's owner (that is the point), so Mist is the one module where the gardener's recipients are not verified by the contract; what every holder can verify is that their own notes arrive and add up to their share. Small rounds are small crowds, and a withdrawal right after a round, of a denomination only one holder got, tells a lot; the crowd is every note of that denomination ever sown, across all Mist coins. The circuit's trusted setup matters: a deploy must be built on the public powers of tau (zk/build.mjs says how), and the deploy script refuses a development setup on mainnet.</p>
      <p>Check it rather than trust it: the pool and its verifier are verified on Etherscan, every note, round and spend is an event anyone can read, and the repository's <span className="mono">scripts/mist.mjs</span> makes a proof in a terminal, asks the verifier on mainnet, and prints a coin's whole mist trail with its transactions.</p>

      <h2 id="gardener">The gardener</h2>
      <p>The gardener is the one hot key the platform runs, funded by the platform's 20%. It collects fees, pays modules, opens clover draws, sows mist rounds and relays mist withdrawals, so nobody else pays gas for a coin's housekeeping. The contract bounds it: a coin's pot can only go to that coin's holders, that coin's buyback or that coin's stock, with every recipient checked to hold the coin, or into mist notes nobody can spend without a proof. It cannot send a pot anywhere else, cannot touch the platform's share, cannot change a module and cannot touch the liquidity.</p>
      <p>A clover draw is checkable by anyone: the gardener commits to a block three ahead; once it is in, its hash modulo the total balance picks a point on the line of holders sorted by address, and the holder it falls in wins. The block, the hash and the winner are in the event.</p>
      <p>It works in thresholds and in patience, so gas never eats a payout: a coin's pool fees are collected at once from 0.02 ETH and a pot is paid at once from 0.05 ETH; under that, a coin is still tended every fifteen minutes as long as what is due is worth ten times its gas at the moment's gas price. A holder's share under 0.0003 ETH waits in the pot for the next round, and nothing is sent while gas is over the cap. A coin that shows nothing paid out has not earned ten times a payout's gas yet. Roots and Branch need none of this: the fees contract pushes their share the moment it lands.</p>

      <h2 id="names">Names</h2>
      <p>Anyone can launch a coin here under any name or symbol; the launchpad has no say in it, and that is the point. So the site marks what it knows: the platform's own coin wears an official chip and comes first, and any other coin wearing its name or its symbol is marked a lookalike, with a link to the real one on its page. Check the address before you trade; a name is not an address. A coin the site keeps out of its lists keeps its page, its pool and its module; the chain does not forget.</p>

      <h2 id="stocks">Stocks</h2>
      <p>The Harvest module buys tokenized stocks: ERC-20s on Ethereum issued against real shares. The platform allows each one on chain and keeps a route for it through a Uniswap pool, v3 or v4; only stocks with real liquidity get a route, the rest wait. Issuers may bar some jurisdictions from holding their tokens; a holder the issuer blocks gets a claimable balance in the fees contract instead of the payout, pulled from the Me page.</p>

      <h2 id="contracts">The contracts</h2>
      <p><b>Halcyon</b> (the launchpad): launches coins and seeds pools. No privileged function at all. <b>HalcyonFees</b>: takes every collect, splits it 80/20, holds pots and claimable balances, runs the modules under the gardener's bounds; the platform wallet can withdraw its own pot, rotate the gardener and allow stocks, nothing else. <b>HalcyonLocker</b> and <b>HalcyonV4Locker</b>: hold every position forever and collect its fees for the gardener. <b>HalcyonHook</b>: the v4 rules. <b>HalcyonSwap</b>: the simplest router for v4 pools, used by the site and the gardener; anyone may use it. <b>HalcyonToken</b>: the coin, an EIP-1167 clone of one verified implementation. <b>HalcyonMist</b>: the pool of private notes, with its Poseidon hash and its Groth16 verifier.</p>
      {cfg?.launchpad ? <>
        <p>Deployed on {cfg.chainName}{cfg.deployBlock ? <> from block {cfg.deployBlock.toLocaleString('en-US')}</> : null}{cfg.deployment?.at ? <> ({new Date(cfg.deployment.at).toISOString().slice(0, 10)})</> : null}. Every address below is the one the site and the gardener use.</p>
        <div className="card scroll-x" style={{ padding: 0 }}><table className="tbl"><thead><tr><th>Contract</th><th>Role</th><th>Address</th></tr></thead><tbody>
          {([
            ['Halcyon', 'the launchpad', cfg.launchpad], ['HalcyonFees', 'fees, pots, modules', cfg.fees], ['HalcyonLocker', 'v3 positions, locked', cfg.locker], ['HalcyonV4Locker', 'v4 positions, locked', cfg.v4Locker], ['HalcyonHook', 'the rules of v4 pools', cfg.hook], ['HalcyonSwap', 'a router for v4 pools', cfg.swap], ['HalcyonToken', 'the coin implementation (cloned)', cfg.tokenImpl], ['HalcyonMist', 'the pool of private notes', cfg.mist],
            ['PoseidonT3', 'the hash of the mist tree', cfg.deployment?.poseidon || ''], ['MistVerifier', 'the Groth16 verifier', cfg.deployment?.verifier || ''], ['Create2Deployer', 'placed the hook at its address', cfg.deployment?.create2 || ''],
          ] as [string, string, string][]).filter(r => r[2] && !/^0x0{40}$/.test(r[2])).map(([name, role, address]) => <tr key={name}><td><b>{name}</b></td><td className="muted">{role}</td><td className="mono small">{cfg.explorer ? <a href={`${cfg.explorer}/address/${address}`} target="_blank" rel="noreferrer">{address}</a> : address}</td></tr>)}
        </tbody></table></div>
        <p className="small muted" style={{ marginTop: 10 }}>The platform wallet is {cfg.explorer && cfg.platform ? <a href={`${cfg.explorer}/address/${cfg.platform}`} target="_blank" rel="noreferrer" className="mono">{cfg.platform}</a> : <span className="mono">{cfg.platform || 'unset'}</span>}. Uniswap's own contracts the launchpad builds on: v3 factory <span className="mono">{short(cfg.uniswap.v3Factory, 6)}</span>, position manager <span className="mono">{short(cfg.uniswap.nfpm, 6)}</span>, SwapRouter02 <span className="mono">{short(cfg.uniswap.swapRouter02, 6)}</span>, v4 PoolManager <span className="mono">{short(cfg.uniswap.poolManager, 6)}</span>; Chainlink's ETH/USD feed prices every launch.{cfg.zk && !cfg.zk.dev && cfg.zk.ptau ? <> The mist circuit ({cfg.zk.constraints.toLocaleString('en-US')} constraints, Groth16 over BN254) was set up on <span className="mono">{cfg.zk.ptau}</span>, the Ethereum Foundation PSE's Perpetual Powers of Tau prepared for phase 2, with one Halcyon contribution whose entropy was never written down.</> : null}</p>
      </> : <p className="small muted">This is the demo: sample coins and no chain behind them, so no addresses here. The live site lists every contract with its Etherscan link.</p>}
      <p>All of it is open source, verified on Etherscan and tested against the real Uniswap v3 and v4 bytecode. Set slippage to 2% or more when trading a Halcyon coin in another terminal.</p>
    </main>
  );
}
