import { Link } from 'react-router-dom';
import { useConfig, useTitle } from '../lib/hooks';
import { ModuleIcon } from '../components/CoinCard';
import type { ModuleId } from '../lib/api';

const DETAIL: Record<ModuleId, { who: string; how: string; when: string }> = {
  roots: { who: 'Creators who fund their work with the coin.', how: 'Every collect lands in HalcyonFees and 80% of it is pushed to the creator in the same transaction. A creator contract that refuses ETH gets a claimable balance instead.', when: 'Every collect, from the first one.' },
  rain: { who: 'Coins that want to pay their community for holding.', how: 'The 80% waits in the coin\'s pot. When the pot is worth paying, the gardener reads every holder, computes each share pro rata to the balance, and pays them in ETH in batches. Shares below the minimum stay in the pot for the next round. Only addresses that hold the coin can be paid, by the contract\'s own check.', when: 'Each time the pot passes the gardener\'s threshold, a few times a day for an active coin.' },
  prune: { who: 'Coins that want a shrinking supply.', how: 'The 80% waits in the pot. The gardener buys the coin back through its own pool with it and burns everything it bought, with a minimum output so a sandwich cannot eat the round.', when: 'Each time the pot passes the threshold.' },
  harvest: { who: 'Coins that want dividends in something real.', how: 'The 80% waits in the pot. The gardener buys a tokenized stock from the platform\'s allow-list through its Uniswap pool, v3 or v4, and pays it out to holders of at least 10,000 coins, pro rata. A holder the issuer will not let receive gets a claimable balance.', when: 'Each time the pot passes the threshold; the stock is paid out on the next pass.' },
  branch: { who: 'Teams, charities, a treasury and a founder.', how: 'The creator names up to eight addresses and their shares. Every collect is pushed to them at once, in those shares. The creator can change the branches; the shares always add up to 100%.', when: 'Every collect, from the first one.' },
  clover: { who: 'Coins that want a reason to hold and a story to tell.', how: 'The 80% waits in the pot. When it is worth paying, the gardener opens a draw on a block three ahead. Once that block is in, its hash picks one holder, weighted by balance, and the gardener pays the whole pot to them. The block, the hash and the winner are in the record, so anyone can check the draw from the holders at that moment.', when: 'Each time the pot passes the threshold.' },
  rings: { who: 'Coins that want to reward the patient.', how: 'Like Rain, but each share is weighted by balance times days held: a day at least, thirty at most. A wallet that has held for a month weighs thirty times one that bought today, for the same bag. Selling to zero resets the clock.', when: 'Each time the pot passes the threshold.' },
  mist: { who: 'Coins whose holders would rather not have their income read off the chain.', how: 'The 80% waits in the pot. A holder registers a mist key once (two public keys, derived in the browser from one signature). Each round the gardener cuts every keyed holder\'s share into notes of the pool\'s denominations (the remainder by lot) and sows them into the mist pool: each note a commitment only that holder can find, in a Merkle tree the pool keeps. Spending a note is a zero-knowledge proof made in the holder\'s browser: it shows the note is in the tree and the spending key is theirs, reveals a nullifier so it spends once, and pays any address through a relayer. Holders without a key are paid in the open.', when: 'Each time the pot passes the threshold.' },
};
export default function Modules() {
  const cfg = useConfig(); useTitle(`Modules · ${cfg?.siteName || 'Halcyon'}`);
  return (
    <main className="wrap page">
      <h1 style={{ fontSize: '2.4rem' }}>Modules</h1><p className="muted" style={{ margin: '6px 0 22px', maxWidth: 680 }}>Every Halcyon coin pays 1% on every trade, to a pool Halcyon holds for it. 20% of that runs the platform and the gardener. The other 80% does one of eight things, chosen at launch and changeable by the creator.</p>
      <div className="stack">{cfg && (Object.keys(cfg.modules) as ModuleId[]).map(id => <section key={id} className="card pad modulecard"><span className={`ic ${id}`}><ModuleIcon id={id} size={26} /></span><div style={{ flex: 1 }}><h2 style={{ fontSize: '1.5rem' }}>{cfg.modules[id].name}</h2><p className="muted" style={{ margin: '4px 0 12px' }}>{cfg.modules[id].line}</p><div className="grid cols-3"><div><label className="lbl">For</label><p className="small" style={{ margin: 0 }}>{DETAIL[id].who}</p></div><div><label className="lbl">How</label><p className="small" style={{ margin: 0 }}>{DETAIL[id].how}</p></div><div><label className="lbl">When</label><p className="small" style={{ margin: 0 }}>{DETAIL[id].when}</p></div></div></div></section>)}</div>
      <h2 style={{ marginTop: 32 }}>The rules pool</h2><p className="muted" style={{ margin: '6px 0 16px', maxWidth: 680 }}>A coin can launch on Uniswap v4 with the Halcyon hook instead of a plain v3 pool. The creator sets rules once; Uniswap enforces them on every swap, whoever routes it.</p>
      <div className="grid cols-4">
        <div className="card pad"><h3>The opening fee</h3><p className="small muted">Buys in the first minutes pay a fee that starts where the creator set it (up to 90%) and falls in a straight line to 1% over the window. A sniper in the first block pays most of the buy to the pool. The pool's fees are the coin's, so snipers pay the holders.</p></div>
        <div className="card pad"><h3>The max per swap</h3><p className="small muted">During the same window no single swap may take more than the creator's share of the supply (1%, 2% or 5%). Splitting a big buy into many does not help: each pays the opening fee.</p></div>
        <div className="card pad"><h3>The sell fee</h3><p className="small muted">Sells can pay more than buys, forever (1% to 5%). The extra goes to the pool like every fee, so a coin that is sold hard pays its holders more.</p></div>
        <div className="card pad"><h3>One liquidity provider</h3><p className="small muted">Only the Halcyon locker may add liquidity to a rules pool, so every fee the pool ever charges goes to the coin's position. Nobody can dilute it or front-run it with a position of their own.</p></div>
      </div>
      <div className="card pad" style={{ marginTop: 22 }}><h3>What the gardener can and cannot do</h3><p className="muted small">The gardener is one address the platform runs. The contract lets it move a coin's pot only into that coin's holders, that coin's burn or that coin's stock, with every recipient checked to hold the coin. It cannot send a pot anywhere else, cannot touch the platform's share, cannot change a module and cannot touch the liquidity, which no address can. Mist is the one exception the chain cannot check: a note's commitment belongs to nobody the contract can name, so there the gardener's honesty shows in the notes it sows, which every holder can check against their own share. The creator changes the module from the coin's page. <Link to="/docs#gardener">More in the docs →</Link></p></div>
    </main>
  );
}
